const express=require('express'),QRCode=require('qrcode'),axios=require('axios'),{default:makeWASocket,useMultiFileAuthState,DisconnectReason,downloadMediaMessage}=require('@whiskeysockets/baileys'),path=require('path'),fs=require('fs');
const app=express(),PORT=process.env.PORT||3000,GWURL=process.env.GOOGLE_WEBHOOK_URL||"https://script.google.com/macros/s/AKfycbyiAvghPgf9ONIyxWDG2WVVCU1Zpuy7MFtwJQxXakdVlHdpE7PH0IvnzefGzjZlwT40/exec";
let qrData="",online=false,sock=null;
const sess={},BANCOS=["Itaú","Caixa Econômica","Bradesco","Santander","Banco do Brasil"];
app.use(express.json());
const noop=()=>{},log={level:'silent',trace:noop,debug:noop,info:noop,warn:noop,error:noop,fatal:noop,isLevelEnabled:()=>false,child:()=>log};
setInterval(()=>axios.get("https://whatsapp-crm-correspondente.onrender.com").catch(()=>{}),4*60*1000);
app.get('/logout',async(req,res)=>{online=false;qrData="";if(sock){try{sock.logout();sock.end();}catch(e){}}const f=path.join(__dirname,'auth_info');if(fs.existsSync(f))fs.rmSync(f,{recursive:true,force:true});setTimeout(start,1500);res.send('<html><head><meta http-equiv="refresh" content="4;url=/"></head><body style="text-align:center;padding:50px"><h2>🔄 Resetando... aguarde.</h2></body></html>');});
app.post('/notificar-aprovacao',async(req,res)=>{try{const{idProposta,nomeCliente,cpf,telefoneCliente,whatsappImobiliaria}=req.body;if(!sock||!online)return res.status(503).json({status:"error"});if(whatsappImobiliaria){const j=whatsappImobiliaria.includes('@')?whatsappImobiliaria:`${whatsappImobiliaria.replace(/\D/g,'')}@s.whatsapp.net`;await sock.sendMessage(j,{text:`🎉 *Aprovado!* Cliente *${idProposta} - ${nomeCliente} (CPF: ${cpf})* está *APROVADO*!`}).catch(()=>{});}await new Promise(r=>setTimeout(r,1500));if(telefoneCliente){const j=`${telefoneCliente.replace(/\D/g,'')}@s.whatsapp.net`;await sock.sendMessage(j,{text:`🎉 Sua proposta está *APROVADA*!\n\n_(O Robô não responderá nesta conversa)_`}).catch(()=>{});}return res.json({status:"success"});}catch(e){return res.status(500).json({status:"error",message:e.toString()});}});
app.get('/',async(req,res)=>{if(online)return res.send('<html><body style="text-align:center;padding:50px"><h1>✅ BOT CONECTADO!</h1><a href="/logout">🔄 Resetar</a></body></html>');if(!qrData)return res.send('<html><head><meta http-equiv="refresh" content="3"></head><body style="text-align:center;padding:50px"><h2>⏳ Gerando QR Code...</h2></body></html>');try{const img=await QRCode.toDataURL(qrData);res.send(`<html><head><meta http-equiv="refresh" content="12"></head><body style="text-align:center;padding:30px"><h2>📱 Escaneie para conectar</h2><img src="${img}" width="280"/><br/><a href="/logout">🔄 Novo QR</a></body></html>`);}catch(e){res.send("Erro QR");}});
async function verifyImob(nome){try{const r=await axios.get(`${GWURL}?action=verifyName&name=${encodeURIComponent(nome)}`);if(r.data&&r.data.found)return{valido:true,imobiliaria:r.data.imobiliaria,codigo:r.data.codigo};}catch(e){}return{valido:false};}
async function cadastrarImob(nome,tel,bairro){try{const r=await axios.post(GWURL,{action:"cadastrarImobiliaria",nome,telefone:tel,bairro});if(r.data&&(r.data.imobiliaria||r.data.nome))return{nome:r.data.imobiliaria||r.data.nome,codigo:r.data.codigo};}catch(e){}return null;}
function gerarTexto(s){let t=`Imobiliária: ${s.imob||''}\nCliente 1: ${s.n1||''}\nCPF 1: ${s.c1||''}\nTelefone 1: ${s.t1||''}\nBanco: ${s.banco||''}\n`;if(s.p2)t+=`Cliente 2: ${s.n2||''}\nCPF 2: ${s.c2||''}\nTelefone 2: ${s.t2||''}\n`;t+=`Compra/Venda: ${s.cv||''}\nFinanciamento: ${s.fin||''}\nEntrada: ${s.ent||''}\nObservação: ${s.obs||'Nenhuma'}`;return t;}
async function resumo(from,s){let r=`📋 *RESUMO:*\n\n🏢 Imobiliária: ${s.imob}\n👤 Prop 1: ${s.n1}\n💳 CPF: ${s.c1}\n📱 Tel: ${s.t1}\n🏦 Banco: ${s.banco}\n`;if(s.p2)r+=`👥 Prop 2: ${s.n2} (CPF:${s.c2} Tel:${s.t2})\n`;r+=`🏠 C/V: R$${s.cv}\n💰 Fin: R$${s.fin}\n💵 Entrada: R$${s.ent}\n📁 Docs: ${s.docs.length}\n📝 Obs: ${s.obs||'Nenhuma'}\n\n1️⃣ CONFIRMAR\n2️⃣ CORRIGIR`;s.step='CONFIRM';await sock.sendMessage(from,{text:r}).catch(()=>{});}
