const express=require('express'),QRCode=require('qrcode'),axios=require('axios'),{default:makeWASocket,useMultiFileAuthState,DisconnectReason,downloadMediaMessage}=require('@whiskeysockets/baileys'),path=require('path'),fs=require('fs');
const app=express(),PORT=process.env.PORT||3000,GWURL=process.env.GOOGLE_WEBHOOK_URL||"https://script.google.com/macros/s/AKfycbyiAvghPgf9ONIyxWDG2WVVCU1Zpuy7MFtwJQxXakdVlHdpE7PH0IvnzefGzjZlwT40/exec";
let qrData="",online=false,sock=null;
const sess={},BANCOS=["Itaú","Caixa Econômica","Bradesco","Santander","Banco do Brasil"];
app.use(express.json());
const noop=()=>{},log={level:'silent',trace:noop,debug:noop,info:noop,warn:noop,error:noop,fatal:noop,isLevelEnabled:()=>false,child:()=>log};
setInterval(()=>axios.get("https://whatsapp-crm-correspondente.onrender.com").catch(()=>{}),4*60*1000);
app.get('/logout',async(req,res)=>{online=false;qrData="";if(sock){try{sock.logout();sock.end();}catch(e){}}const f=path.join(__dirname,'auth_info');if(fs.existsSync(f))fs.rmSync(f,{recursive:true,force:true});setTimeout(start,1500);res.send('<html><head><meta http-equiv="refresh" content="4;url=/"></head><body style="text-align:center;padding:50px"><h2>🔄 Resetando... aguarde.</h2></body></html>');});
app.post('/notificar-aprovacao',async(req,res)=>{try{const{idProposta,nomeCliente,cpf,telefoneCliente,whatsappImobiliaria}=req.body;if(!sock||!online)return res.status(503).json({status:"error"});if(whatsappImobiliaria){const j=whatsappImobiliaria.includes('@')?whatsappImobiliaria:`${whatsappImobiliaria.replace(/\D/g,'')}@s.whatsapp.net`;await sock.sendMessage(j,{text:`🎉 *Aprovado!* Cliente *${idProposta} - ${nomeCliente} (CPF: ${cpf})* está *APROVADO*!`}).catch(()=>{});}await new Promise(r=>setTimeout(r,1500));if(telefoneCliente){const j=`${telefoneCliente.replace(/\D/g,'')}@s.whatsapp.net`;await sock.sendMessage(j,{text:`🎉 Sua proposta está *APROVADA*!\n\n_(O Robô não responderá nesta conversa)_`}).catch(()=>{});}return res.json({status:"success"});}catch(e){return res.status(500).json({status:"error",message:e.toString()});}});
app.get('/',async(req,res)=>{if(online)return res.send('<html><body style="text-align:center;padding:50px"><h1>✅ BOT CONECTADO!</h1><a href="/logout">🔄 Resetar</a></body></html>');if(!qrData)return res.send('<html><head><meta http-equiv="refresh" content="3"></head><body style="text-align:center;padding:50px"><h2>⏳ Gerando QR Code...</h2></body></html>');try{const img=await QRCode.toDataURL(qrData);res.send(`<html><head><meta http-equiv="refresh" content="12"></head><body style="text-align:center;padding:30px"><h2>📱 Escaneie para conectar</h2><img src="${img}" width="280"/><br/><a href="/logout">🔄 Novo QR</a></body></html>`);}catch(e){res.send("Erro QR");}});
async function verifyImob(nome){try{const r=await axios.get(`${GWURL}?action=verifyName&name=${encodeURIComponent(nome)}`);if(r.data&&r.data.found)return{valido:true,imobiliaria:r.data.imobiliaria,codigo:r.data.codigo};}catch(e){}return{valido:false};}
async function cadastrarImob(nome,tel,bairro){try{const r=await axios.post(GWURL,{action:"cadastrarImobiliaria",nome,telefone:tel,bairro});if(r.data&&(r.data.imobiliaria||r.data.nome))return{nome:r.data.imobiliaria||r.data.nome,codigo:r.data.codigo};}catch(e){}return null;}
function gerarTexto(s){let t=`Imobiliária: ${s.imob||''}\nCliente 1: ${s.n1||''}\nCPF 1: ${s.c1||''}\nTelefone 1: ${s.t1||''}\nBanco: ${s.banco||''}\n`;if(s.p2)t+=`Cliente 2: ${s.n2||''}\nCPF 2: ${s.c2||''}\nTelefone 2: ${s.t2||''}\n`;t+=`Compra/Venda: ${s.cv||''}\nFinanciamento: ${s.fin||''}\nEntrada: ${s.ent||''}\nObservação: ${s.obs||'Nenhuma'}`;return t;}
async function resumo(from,s){let r=`📋 *RESUMO:*\n\n🏢 Imobiliária: ${s.imob}\n👤 Prop 1: ${s.n1}\n💳 CPF: ${s.c1}\n📱 Tel: ${s.t1}\n🏦 Banco: ${s.banco}\n`;if(s.p2)r+=`👥 Prop 2: ${s.n2} (CPF:${s.c2} Tel:${s.t2})\n`;r+=`🏠 C/V: R$${s.cv}\n💰 Fin: R$${s.fin}\n💵 Entrada: R$${s.ent}\n📁 Docs: ${s.docs.length}\n📝 Obs: ${s.obs||'Nenhuma'}\n\n1️⃣ CONFIRMAR\n2️⃣ CORRIGIR`;s.step='CONFIRM';await sock.sendMessage(from,{text:r}).catch(()=>{});}
async function start(){const af=path.join(__dirname,'auth_info');try{if(!fs.existsSync(af))fs.mkdirSync(af,{recursive:true});const{state,saveCreds}=await useMultiFileAuthState(af);sock=makeWASocket({auth:state,logger:log,printQRInTerminal:false,browser:['CRM','Chrome','1.0'],syncFullHistory:false});sock.ev.on('creds.update',saveCreds);sock.ev.on('connection.update',u=>{if(u.qr){qrData=u.qr;online=false;}if(u.connection==='open'){online=true;qrData="";}if(u.connection==='close'){online=false;const c=u.lastDisconnect?.error?.output?.statusCode;if(c===DisconnectReason.loggedOut||c===401||c===403){if(fs.existsSync(af))fs.rmSync(af,{recursive:true,force:true});}setTimeout(start,3000);}});sock.ev.on('messages.upsert',async m=>{try{if(!m.messages||!m.messages.length)return;const msg=m.messages[0];if(!msg?.message||msg.key.fromMe)return;const from=msg.key.remoteJid;if(!from||from.endsWith('@g.us')||from==='status@broadcast')return;const text=(msg.message.conversation||msg.message.extendedTextMessage?.text||msg.message.imageMessage?.caption||msg.message.documentMessage?.caption||'').trim();const tl=text.toLowerCase();let s=sess[from];
if(!s||['inicio','reiniciar','menu','cancelar','sair'].includes(tl)){sess[from]={step:'IMOB',docs:[]};await sock.sendMessage(from,{text:"👋 *Bem-vindo!*\n\nDigite o nome da imobiliária:\n_(Sem cadastro? Digite *CADASTRO*)_"}).catch(()=>{});return;}
if(s.step==='EDIT'){text.split('\n').forEach(l=>{const p=l.split(':');if(p.length>=2){const k=p[0].toLowerCase().trim(),v=p.slice(1).join(':').trim();if(k.includes('imob'))s.imob=v;else if(k.includes('cliente 1'))s.n1=v;else if(k.includes('cpf 1'))s.c1=v;else if(k.includes('telefone 1'))s.t1=v.replace(/\D/g,'');else if(k.includes('banco'))s.banco=v;else if(k.includes('cliente 2'))s.n2=v;else if(k.includes('cpf 2'))s.c2=v;else if(k.includes('telefone 2'))s.t2=v.replace(/\D/g,'');else if(k.includes('compra'))s.cv=v;else if(k.includes('financiamento'))s.fin=v;else if(k.includes('entrada'))s.ent=v;else if(k.includes('obs'))s.obs=v;}});await sock.sendMessage(from,{text:"✅ Dados atualizados!"});await resumo(from,s);return;}
if(s.step==='CONFIRM'){if(text==='1'||tl.includes('confirmar')){await sock.sendMessage(from,{text:"⏳ Enviando..."});try{const p1={imobiliaria:s.imob,nomeCliente:s.n1,tipoProponente:"Proponente 1",cpf:s.c1,telefone:s.t1,banco:s.banco,valorCompraVenda:s.cv,valorFinanciamento:s.fin,valorEntrada:s.ent,observacao:s.obs||"Nenhuma",whatsappOrigem:from,documentos:s.docs};const r1=await axios.post(GWURL,p1);const id=r1.data.idProposta||"ID";const url=r1.data.pastaUrl||"";if(s.p2){await axios.post(GWURL,{idProposta:id,imobiliaria:s.imob,nomeCliente:s.n2,tipoProponente:"Proponente 2",cpf:s.c2,telefone:s.t2,banco:s.banco,valorCompraVenda:s.cv,valorFinanciamento:s.fin,valorEntrada:s.ent,observacao:s.obs||"Nenhuma",whatsappOrigem:from});}await sock.sendMessage(from,{text:`🎉 *PROPOSTA ENVIADA!*\n\n📍 ID: ${id}\n📂 Drive: ${url}`});if(s.t1)await sock.sendMessage(`${s.t1}@s.whatsapp.net`,{text:`🎉 Sua proposta está em análise no *${s.banco}*!\n\n_(O Robô não responderá nesta conversa)_`}).catch(()=>{});delete sess[from];}catch(e){await sock.sendMessage(from,{text:"⚠️ Erro ao salvar. Digite *inicio* para tentar novamente."});}}else if(text==='2'||tl.includes('corrigir')){s.step='EDIT';await sock.sendMessage(from,{text:"✏️ Copie, corrija e reenvie:"});await sock.sendMessage(from,{text:gerarTexto(s)});}return;}
switch(s.step){case 'IMOB':if(['cadastro','cadastrar'].includes(tl)){s.step='CN';await sock.sendMessage(from,{text:"🏢 Nome da imobiliária:"});return;}await sock.sendMessage(from,{text:"⏳ Verificando..."});const b=await verifyImob(text);if(b.valido){s.imob=b.imobiliaria;s.step='N1';await sock.sendMessage(from,{text:`✅ *${b.imobiliaria}* encontrada!\n\nNome completo do cliente (Prop 1):`});}else await sock.sendMessage(from,{text:`⚠️ Imobiliária *"${text}"* não encontrada.\nVerifique ou digite *CADASTRO*.`});break;
case 'CN':s.iNome=text;s.step='CT';await sock.sendMessage(from,{text:"📱 Telefone da imobiliária:"});break;
case 'CT':s.iTel=text;s.step='CB';await sock.sendMessage(from,{text:"📍 Bairro da imobiliária:"});break;
case 'CB':const ni=await cadastrarImob(s.iNome,s.iTel,text);if(ni){s.imob=ni.nome;s.step='N1';await sock.sendMessage(from,{text:`🎉 Cadastrada: *${ni.nome}*\n\nNome do cliente (Prop 1):`});}else{await sock.sendMessage(from,{text:"⚠️ Falha. Digite *inicio*."});delete sess[from];}break;
case 'N1':s.n1=text;s.step='C1';await sock.sendMessage(from,{text:`👤 *${text}*\n\nCPF do Prop 1:`});break;
case 'C1':s.c1=text;s.step='T1';await sock.sendMessage(from,{text:"📱 Telefone Prop 1 (com DDD):"});break;
case 'T1':s.t1=text.replace(/\D/g,'');s.step='BANCO';await sock.sendMessage(from,{text:`📱 *${s.t1}*\n\n🏦 Banco:\n1️⃣ Itaú\n2️⃣ Caixa Econômica\n3️⃣ Bradesco\n4️⃣ Santander\n5️⃣ Banco do Brasil`});break;
case 'BANCO':s.banco=BANCOS[parseInt(text)-1]||text;s.step='DOCS';await sock.sendMessage(from,{text:`🏦 *${s.banco}*\n\n📷 Envie documentos do Prop 1.\nQuando terminar, digite *PRONTO*:`});break;
case 'DOCS':if(msg.message.imageMessage||msg.message.documentMessage){try{const buf=await downloadMediaMessage(msg,'buffer');const mime=msg.message.imageMessage?.mimetype||msg.message.documentMessage?.mimetype||"image/jpeg";s.docs.push({nomeArquivo:`doc_${Date.now()}.${mime.includes('pdf')?'pdf':'jpg'}`,mimeType:mime,base64:buf.toString('base64')});await sock.sendMessage(from,{text:`✅ Doc ${s.docs.length} recebido!`});}catch(e){}return;}if(tl==='pronto'){s.step='P2';await sock.sendMessage(from,{text:`✅ *${s.docs.length} doc(s)* salvos.\n\n❓ Existe 2º proponente?\n1️⃣ SIM\n2️⃣ NÃO`});}else await sock.sendMessage(from,{text:"Envie docs ou digite *PRONTO*."});break;
case 'P2':if(text==='1'||tl==='sim'){s.p2=true;s.step='N2';await sock.sendMessage(from,{text:"Nome do 2º Proponente:"});}else{s.p2=false;s.step='CV';await sock.sendMessage(from,{text:"📌 Valor de Compra e Venda (ex: 500.000):"});}break;
case 'N2':s.n2=text;s.step='C2';await sock.sendMessage(from,{text:"CPF do 2º Proponente:"});break;
case 'C2':s.c2=text;s.step='T2';await sock.sendMessage(from,{text:"Telefone do 2º Proponente:"});break;
case 'T2':s.t2=text.replace(/\D/g,'');s.step='CV';await sock.sendMessage(from,{text:"📌 Valor de Compra e Venda (ex: 500.000):"});break;
case 'CV':s.cv=text;s.step='FIN';await sock.sendMessage(from,{text:"💰 Valor do Financiamento (ex: 400.000):"});break;
case 'FIN':s.fin=text;s.step='ENT';await sock.sendMessage(from,{text:"💵 Valor da Entrada (ex: 100.000):"});break;
case 'ENT':s.ent=text;s.step='OBS';await sock.sendMessage(from,{text:"📝 Alguma observação?\n1️⃣ NÃO\n2️⃣ SIM"});break;
case 'OBS':if(text==='1'||tl==='nao')s.obs="Nenhuma";else if(text==='2'){s.step='OBSTEXT';await sock.sendMessage(from,{text:"Digite sua observação:"});return;}else s.obs=text;await resumo(from,s);break;
case 'OBSTEXT':s.obs=text;await resumo(from,s);break;}}catch(e){}});}catch(err){const af=path.join(__dirname,'auth_info');if(fs.existsSync(af))fs.rmSync(af,{recursive:true,force:true});setTimeout(start,5000);}}
app.listen(PORT,()=>{console.log(`Servidor na porta ${PORT}`);start();});
